import type { Product } from "./schema/products";
import type { Region } from "./schema/regions";
import type { Distributor } from "./schema/distributors";

export const SEED_REGIONS: Omit<Region, "id">[] = [
  {
    code: "CR",
    name: "Costa Rica",
    currency: "CRC",
    phone: "+506 8800 2090",
    email: "cr@dynamex.mx",
    address: "Zona Franca Coyol, Alajuela, Costa Rica",
    whatsapp: "50688002090",
    distributionTime: "24–48 hrs",
    isActive: true,
  },
  {
    code: "CO",
    name: "Colombia",
    currency: "COP",
    phone: "+57 310 555 0192",
    email: "colombia@dynamex.mx",
    address: "Bogotá D.C., Colombia",
    whatsapp: "573105550192",
    distributionTime: "3–5 días hábiles",
    isActive: true,
  },
  {
    code: "EC",
    name: "Ecuador",
    currency: "USD",
    phone: "+593 99 555 0174",
    email: "ecuador@dynamex.mx",
    address: "Quito, Pichincha, Ecuador",
    whatsapp: "593995550174",
    distributionTime: "3–5 días hábiles",
    isActive: true,
  },
];

export const SEED_PRODUCTS: Omit<Product, "id">[] = [
  {
    name: "Convertidor Universal Euro 4",
    sku: "DMX-CAT-E4-001",
    category: "convertidor_catalitico",
    description:
      "Convertidor catalítico de cerámica de alto flujo para motor 4 cilindros. Certificación Euro 4.",
    technicalSpecs: {
      material: "Cerámica 400 cpsi",
      longitud: "12 pulgadas",
      diametro: "4 pulgadas",
      entrada: "2 pulgadas",
      aplicacion: "Universal gasolina 1.6L-2.4L",
      emisiones: "Euro 4",
    },
    compatibleBrands: ["Nissan", "Toyota", "Honda", "Mazda"],
    certifications: ["Euro 4", "EPA Tier 2"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: true,
  },
  {
    name: "Convertidor Pickup Diesel DPF",
    sku: "DMX-DPF-002",
    category: "convertidor_catalitico",
    description:
      "Filtro de partículas diesel (DPF) para pickups 2.5L-3.0L. Regeneración activa compatible.",
    technicalSpecs: {
      material: "Filtro cerámico cordierita",
      aplicacion: "Diesel 2.5L-3.0L",
      entrada: "2.5 pulgadas",
      emisiones: "Euro 5",
    },
    compatibleBrands: ["Ford", "Chevrolet", "RAM", "Mitsubishi"],
    certifications: ["Euro 5"],
    imageUrl: "/images/products/dpf-filter.svg",
    isFeatured: true,
  },
  {
    name: "Línea de Escape Completa Inox",
    sku: "DMX-ESC-003",
    category: "escape",
    description:
      "Línea de escape completa en acero inoxidable 304. Incluye silenciador deportivo y abrazaderas.",
    technicalSpecs: {
      material: "Acero inoxidable 304",
      diametro: "2.5 pulgadas",
      piezas: "3 secciones + abrazaderas",
      garantia: "3 años",
    },
    compatibleBrands: ["Volkswagen", "Seat", "Audi"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/exhaust-system.svg",
    isFeatured: true,
  },
  {
    name: "Convertidor Compacto 3 Cilindros",
    sku: "DMX-CAT-C3-004",
    category: "convertidor_catalitico",
    description: "Diseño compacto para vehículos urbanos 3 cilindros y motores híbridos ligeros.",
    technicalSpecs: {
      material: "Sustrato metálico",
      longitud: "9 pulgadas",
      entrada: "1.75 pulgadas",
      emisiones: "Euro 5",
    },
    compatibleBrands: ["Suzuki", "Hyundai", "Kia", "Chevrolet"],
    certifications: ["Euro 5"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: false,
  },
  {
    name: "Silenciador Deportivo Oval",
    sku: "DMX-SIL-005",
    category: "silenciador",
    description: "Silenciador de alto flujo con acabado cromado. Reducción de backpressure del 35%.",
    technicalSpecs: {
      material: "Acero aluminizado",
      cuerpo: "Ovalado 14 pulgadas",
      entrada: "2.5 pulgadas",
      salida: "3 pulgadas",
    },
    compatibleBrands: ["Universal", "Volkswagen", "Mazda", "Honda"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/muffler.svg",
    isFeatured: false,
  },
  {
    name: "Convertidor Euro 6 Premium",
    sku: "DMX-CAT-E6-006",
    category: "convertidor_catalitico",
    description:
      "Máxima eficiencia de conversión para flotas comerciales. Cumple normativa Euro 6 más reciente.",
    technicalSpecs: {
      material: "Cerámica 600 cpsi",
      entrada: "2.25 pulgadas",
      emisiones: "Euro 6",
      eficiencia: "98% CO / 95% HC",
    },
    compatibleBrands: ["Mercedes-Benz", "BMW", "Volvo", "Hino"],
    certifications: ["Euro 6", "CARB"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: false,
  },
  {
    name: "Convertidor Universal 2.25 Pulgadas",
    sku: "DMX-CAT-U225-007",
    category: "convertidor_catalitico",
    description:
      "Convertidor universal de alto flujo para talleres que requieren adaptación rápida en autos compactos y sedanes.",
    technicalSpecs: {
      material: "Cerámica 400 cpsi",
      longitud: "11 pulgadas",
      entrada: "2.25 pulgadas",
      aplicacion: "Gasolina 1.8L-2.8L",
    },
    compatibleBrands: ["Toyota", "Nissan", "Honda", "Hyundai", "Kia"],
    certifications: ["EPA"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: false,
  },
  {
    name: "Convertidor Universal 2.5 Pulgadas",
    sku: "DMX-CAT-U250-008",
    category: "convertidor_catalitico",
    description:
      "Convertidor universal para motores de mayor cilindrada, pickups ligeras y aplicaciones de alto flujo.",
    technicalSpecs: {
      material: "Cerámica 400 cpsi",
      longitud: "13 pulgadas",
      entrada: "2.5 pulgadas",
      aplicacion: "Gasolina 2.4L-3.5L",
    },
    compatibleBrands: ["Ford", "Chevrolet", "Dodge", "Toyota", "Nissan"],
    certifications: ["EPA", "Euro 5"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: false,
  },
  {
    name: "Convertidor Alto Flujo 3 Pulgadas",
    sku: "DMX-CAT-HF300-009",
    category: "convertidor_catalitico",
    description:
      "Convertidor de alto flujo para proyectos performance y camionetas con línea de escape de 3 pulgadas.",
    technicalSpecs: {
      material: "Sustrato metálico 300 cpsi",
      longitud: "12 pulgadas",
      entrada: "3 pulgadas",
      aplicacion: "Performance / pickup",
    },
    compatibleBrands: ["Ford", "Chevrolet", "Dodge", "Jeep", "Universal"],
    certifications: ["EPA"],
    imageUrl: "/images/products/catalytic-converter.svg",
    isFeatured: false,
  },
  {
    name: "Mofle Cámara Estándar",
    sku: "DMX-SIL-CAM-010",
    category: "silenciador",
    description:
      "Mofle de cámara para reemplazo directo en talleres. Sonido discreto y buena durabilidad diaria.",
    technicalSpecs: {
      material: "Acero aluminizado",
      cuerpo: "Rectangular 18 pulgadas",
      entrada: "2 pulgadas",
      salida: "2 pulgadas",
    },
    compatibleBrands: ["Nissan", "Toyota", "Chevrolet", "Volkswagen"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/muffler.svg",
    isFeatured: false,
  },
  {
    name: "Mofle Redondo Alto Flujo",
    sku: "DMX-SIL-RND-011",
    category: "silenciador",
    description:
      "Silenciador redondo con empaque acústico de fibra cerámica para aplicaciones deportivas controladas.",
    technicalSpecs: {
      material: "Acero inoxidable 409",
      cuerpo: "Redondo 16 pulgadas",
      entrada: "2.5 pulgadas",
      salida: "2.5 pulgadas",
    },
    compatibleBrands: ["Universal", "Honda", "Mazda", "Volkswagen", "Seat"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/muffler.svg",
    isFeatured: false,
  },
  {
    name: "Resonador Compacto Universal",
    sku: "DMX-SIL-RES-012",
    category: "silenciador",
    description:
      "Resonador compacto para reducir vibración y ruido medio sin restringir el flujo del sistema.",
    technicalSpecs: {
      material: "Acero aluminizado",
      cuerpo: "12 pulgadas",
      entrada: "2.25 pulgadas",
      salida: "2.25 pulgadas",
    },
    compatibleBrands: ["Universal", "Toyota", "Hyundai", "Kia", "Nissan"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/muffler.svg",
    isFeatured: false,
  },
  {
    name: "Tubo Flexible Mallado 8 Pulgadas",
    sku: "DMX-FLX-008-013",
    category: "tubo_flexible",
    description:
      "Flexible mallado para reparar fugas, vibración y fatiga en líneas de escape compactas.",
    technicalSpecs: {
      material: "Acero inoxidable mallado",
      longitud: "8 pulgadas",
      entrada: "2 pulgadas",
      aplicacion: "Reparación universal",
    },
    compatibleBrands: ["Universal", "Nissan", "Chevrolet", "Hyundai"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/flexible-pipe.svg",
    isFeatured: false,
  },
  {
    name: "Tubo Flexible Mallado 10 Pulgadas",
    sku: "DMX-FLX-010-014",
    category: "tubo_flexible",
    description:
      "Flexible reforzado para sedanes y SUV ligeras. Absorbe movimiento del motor y protege soldaduras.",
    technicalSpecs: {
      material: "Acero inoxidable mallado",
      longitud: "10 pulgadas",
      entrada: "2.25 pulgadas",
      aplicacion: "Sedán / SUV ligera",
    },
    compatibleBrands: ["Universal", "Toyota", "Honda", "Mazda", "Kia"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/flexible-pipe.svg",
    isFeatured: false,
  },
  {
    name: "Tubo Flexible Mallado 12 Pulgadas",
    sku: "DMX-FLX-012-015",
    category: "tubo_flexible",
    description:
      "Flexible de mayor longitud para camionetas y líneas con más movimiento térmico o mecánico.",
    technicalSpecs: {
      material: "Acero inoxidable mallado",
      longitud: "12 pulgadas",
      entrada: "2.5 pulgadas",
      aplicacion: "Pickup / SUV",
    },
    compatibleBrands: ["Universal", "Ford", "Chevrolet", "Dodge", "Jeep"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/flexible-pipe.svg",
    isFeatured: false,
  },
  {
    name: "Tubo Recto Inox 2 Pulgadas",
    sku: "DMX-ESC-200-016",
    category: "escape",
    description:
      "Tramo recto en acero inoxidable para fabricación y reparación de líneas de escape en taller.",
    technicalSpecs: {
      material: "Acero inoxidable 409",
      longitud: "1 metro",
      diametro: "2 pulgadas",
      pared: "1.5 mm",
    },
    compatibleBrands: ["Universal", "Nissan", "Toyota", "Chevrolet"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/exhaust-system.svg",
    isFeatured: false,
  },
  {
    name: "Tubo Recto Inox 2.5 Pulgadas",
    sku: "DMX-ESC-250-017",
    category: "escape",
    description:
      "Tubo recto de mayor diámetro para sistemas de escape deportivos y camionetas ligeras.",
    technicalSpecs: {
      material: "Acero inoxidable 409",
      longitud: "1 metro",
      diametro: "2.5 pulgadas",
      pared: "1.5 mm",
    },
    compatibleBrands: ["Universal", "Ford", "Volkswagen", "Mazda", "Dodge"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/exhaust-system.svg",
    isFeatured: false,
  },
  {
    name: "Codo Mandril 90 Grados",
    sku: "DMX-ESC-C90-018",
    category: "escape",
    description:
      "Codo mandril para fabricación de bajantes y líneas custom sin reducción agresiva de flujo.",
    technicalSpecs: {
      material: "Acero inoxidable 304",
      diametro: "2.5 pulgadas",
      angulo: "90 grados",
      radio: "Mandril amplio",
    },
    compatibleBrands: ["Universal", "Honda", "Volkswagen", "BMW", "Mercedes-Benz"],
    certifications: ["ISO 9001"],
    imageUrl: "/images/products/exhaust-system.svg",
    isFeatured: false,
  },
];

export const SEED_DISTRIBUTORS: Omit<Distributor, "id" | "createdAt">[] = [
  {
    companyName: "AutoPartes del Valle S.A.",
    contactName: "Carlos Méndez",
    email: "carlos@autopartesvalle.cr",
    phone: "+506 8888 1234",
    country: "Costa Rica",
    city: "San José",
    businessType: "mayorista",
    estimatedMonthlyVolume: "500_1000",
    taxId: "3-101-123456",
    message: null,
    status: "approved",
  },
  {
    companyName: "Repuestos Andinos Ltda.",
    contactName: "María Rodríguez",
    email: "maria@repuestosandinos.co",
    phone: "+57 300 555 7890",
    country: "Colombia",
    city: "Medellín",
    businessType: "distribuidor",
    estimatedMonthlyVolume: "1000_plus",
    taxId: "900123456-1",
    message: null,
    status: "approved",
  },
  {
    companyName: "MotoEscape Ecuador",
    contactName: "Luis Torres",
    email: "luis@motoescape.ec",
    phone: "+593 99 123 4567",
    country: "Ecuador",
    city: "Guayaquil",
    businessType: "taller",
    estimatedMonthlyVolume: "100_500",
    taxId: null,
    message: null,
    status: "pending",
  },
];
